name: Test - Halmos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-halmos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

    steps:
      - name: Install halmos
        run: python3 -m pip install --upgrade halmos

      - name: Run halmos - check caller
        run: halmos
